Add files via upload
isakovaAR/homework pull request #2
Opened 2019-09-30 21:32 UTC by isakovaAR

2019-10-01 14:03 UTC, illarionovEA requested changes
6 нужно доделать

2019-10-19 19:18 UTC, illarionovEA commented
нужно убрать из ноутбука все, что не относится к заданию (остатки кода в конце ноутбука)

2019-10-28 19:17 UTC, isakovaAR commented
Здравствуйте, я загрузила новый файл, там нет мусора после основного кода

2019-11-01 15:54 UTC, illarionovEA approved these changes

2019-12-20 10:13 UTC, merged