Hometask 5
isakovaAR/homework pull request #5
Opened 2019-11-11 22:04 UTC by isakovaAR

2019-11-17 09:33 UTC, illarionovEA requested changes
дз недоделано

2019-11-18 21:18 UTC, isakovaAR commented
Здравствуйте, я доделала оставшиеся задания

2019-11-22 16:10 UTC, illarionovEA commented
распределение в круге не выглядит равномерным
нет задачи на моделирование двумерного гауссовского распределения со средним (3, 6) и ковариационной матрицей ((2, 1), (1, 4))

2019-12-01 12:10 UTC, isakovaAR commented
Здравствуйте, в файле исправлены все ошибки

2019-12-06 15:17 UTC, illarionovEA approved these changes

2019-12-20 10:11 UTC, merged